### PR TITLE
Roll Commands

### PR DESCRIPTION
**Pull request by marloso2**
?roll [_roll string_] / ?r
?reroll [_iterations_] [_roll string_] / ?rr
?randstats [_mode_] / ?rs

Optional tags for rolls:
    **e** - Exploding Dice. If you get a max value on a roll, reroll that die
    **kh** - Keep Highest.
    **kl** - Keep Lowest.

Optional modes for randstats:
    **d20** - Rolls stats with d20s
    **8t18** - Rolls stats with 2d6+6
    **2s** - Rolls two stats with 3d6, two with 4d6kh3 and two with 6d6kh3

### CODE REVIEW

**Comment by ChillFish8** [comment]
Where is this in the files xD

**Comment by marloso2** [comment]
Just look into the Files changed tab

**Comment by ChillFish8** [comment]
yh found it
xD

**Comment by marloso2** [comment]
Neet

**Pull request merged**
